service: task-schedular

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-northeast-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: laravel-vueapp
    distributionFolder: dist/
    indexDocument: index.html
    errorDocument: index.html
